name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: Extension-Builder

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: clone
        run: git clone https://github.com/Biangkerok32/extension-builder.git
      - name: cd extension-builder
        run: cd /path/to/extension-builder/
      - name: update
        run: git pull
      - name: stop
        run: docker stop extension-builder || true
      - name: rm
        run: docker rm extension-builder || true
      - name: build
        run: docker build . -t extension-builder
      - name: run
        run: docker run -d -p 8048:8048 --restart unless-stopped --name="extension-builder" extension-builder

  
